apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web_jenkins
  template:
    metadata:
      labels:
        app: web_jenkins
    spec:
      containers:
        - name: web_jenkins
          image: 621917999036.dkr.ecr.ap-northeast-2.amazonaws.com/web_jenkins:IMAGE_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web_jenkins_service
spec:
  type: LoadBalancer
  selector:
    app: web_jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
